[build]
target = "x86_64-pc-windows-msvc"

rustflags = [
    "-Zpre-link-arg=/NOLOGO",
    "-Zpre-link-arg=/MANIFEST:NO",
    "-Zpre-link-arg=/SUBSYSTEM:WINDOWS",
    "-Zpre-link-arg=/DYNAMICBASE",
    "-Zpre-link-arg=/NXCOMPAT",
    "-Clink-arg=/OPT:REF,ICF",
]
