name: Clippy

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust -> target"

      - name: Add Clippy Component
        working-directory: rust
        run: rustup component add clippy

      - name: Clippy
        working-directory: rust
        run: cargo clippy --all-features -- --deny warnings
